"""empty message

Revision ID: bd8656954d11
Revises: d561631f86e3
Create Date: 2022-12-22 13:30:00.105229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8656954d11'
down_revision = 'd561631f86e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telephone', sa.String(length=12), nullable=False))
        batch_op.add_column(sa.Column('montant', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.drop_column('montant')
        batch_op.drop_column('telephone')

    # ### end Alembic commands ###
