"""empty message

Revision ID: d838ac9a8acf
Revises: 
Create Date: 2022-12-09 13:50:47.772639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd838ac9a8acf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('hashcode',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('password')

    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('hashcode',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('statut')

    # ### end Alembic commands ###
