"""empty message

Revision ID: e33b57ff3ff9
Revises: 6f5f6b4147e8
Create Date: 2023-01-05 16:37:55.668378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33b57ff3ff9'
down_revision = '6f5f6b4147e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consommations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_used', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consommations', schema=None) as batch_op:
        batch_op.drop_column('code_used')

    # ### end Alembic commands ###
