"""empty message

Revision ID: eb6cc7572738
Revises: c434ebd8dc1f
Create Date: 2023-03-07 09:19:11.469998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb6cc7572738'
down_revision = 'c434ebd8dc1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connexions', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connexions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
